spring:
  application.name: stockwellness
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  docker:
    compose:
      enabled: false
  threads.virtual.enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret-key: ${jwt-secret}
  access-token-expiry-ms: 3600000
  refresh-token-expiry-ms: 2592000000

krx:
  service-key: ${krx-secret}
  base-url: https://apis.data.go.kr/1160100/service

logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.apache.hc.client5.http: DEBUG  # 아파치 클라이언트를 쓴다면
    p6spy: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF

---
spring:
  config:
    activate:
      on-profile: test
  batch:
    job:
      enabled: false

krx-secret: "dummy-krx-secret"
krx:
  service-key: "dummy-krx-service-key"

jwt-secret: "dGhpcy1pcy10ZXN0LXNlY3JldC1rZXktZm9yLXN0b2Nrd2VsbG5lc3MtcHJvamVjdC13aGljaC1pcy1zYWZl"
jwt:
  secret-key: "dGhpcy1pcy10ZXN0LXNlY3JldC1rZXktZm9yLXN0b2Nrd2VsbG5lc3MtcHJvamVjdC13aGljaC1pcy1zYWZl"