ALTER TABLE stock_investor_trade
    DROP COLUMN IF EXISTS inst_buying_amt,
    DROP COLUMN IF EXISTS frgn_buying_amt,
    DROP COLUMN IF EXISTS pension_buying_amt,
    DROP COLUMN IF EXISTS trust_buying_amt,
    DROP COLUMN IF EXISTS etc_corp_buying_amt,
    DROP COLUMN IF EXISTS total_net_amt,
    DROP COLUMN IF EXISTS inst_buying_qty,
    DROP COLUMN IF EXISTS frgn_buying_qty,
    DROP COLUMN IF EXISTS pension_buying_qty,
    DROP COLUMN IF EXISTS trust_buying_qty,
    DROP COLUMN IF EXISTS etc_corp_buying_qty,
    DROP COLUMN IF EXISTS total_net_qty,
    DROP COLUMN IF EXISTS prsn_buying_amt,
    DROP COLUMN IF EXISTS prsn_buying_qty,
    ADD COLUMN IF NOT EXISTS name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ticker VARCHAR(20),
    ADD COLUMN IF NOT EXISTS frgn_ntby_qty BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS orgn_ntby_qty BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ivtr_ntby_qty BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bank_ntby_qty BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS insu_ntby_qty BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mrbn_ntby_qty BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fund_ntby_qty BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS etc_orgt_ntby_vol BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS etc_corp_ntby_vol BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS frgn_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS orgn_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ivtr_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bank_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS insu_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mrbn_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fund_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS etc_orgt_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS etc_corp_ntby_tr_pbmn DECIMAL(25, 2) DEFAULT 0;
