-- =============================================================================
-- V1: 초기 전체 스키마 (Flyway 도입 시점의 DB 상태 스냅샷)
-- 이 파일은 기존 DB에 baseline-on-migrate=true 로 적용 시 실행되지 않습니다.
-- 새로운 DB 환경을 구성할 때 사용하세요.
-- =============================================================================

create table if not exists batch_job_instance
(
    job_instance_id bigint       not null
        primary key,
    version         bigint,
    job_name        varchar(100) not null,
    job_key         varchar(32)  not null,
    constraint job_inst_un
        unique (job_name, job_key)
);

create table if not exists batch_job_execution
(
    job_execution_id bigint    not null
        primary key,
    version          bigint,
    job_instance_id  bigint    not null
        constraint job_inst_exec_fk
            references batch_job_instance,
    create_time      timestamp not null,
    start_time       timestamp,
    end_time         timestamp,
    status           varchar(10),
    exit_code        varchar(2500),
    exit_message     varchar(2500),
    last_updated     timestamp
);

create table if not exists batch_job_execution_params
(
    job_execution_id bigint       not null
        constraint job_exec_params_fk
            references batch_job_execution,
    parameter_name   varchar(100) not null,
    parameter_type   varchar(100) not null,
    parameter_value  varchar(2500),
    identifying      char         not null
);

create table if not exists batch_step_execution
(
    step_execution_id  bigint       not null
        primary key,
    version            bigint       not null,
    step_name          varchar(100) not null,
    job_execution_id   bigint       not null
        constraint job_exec_step_fk
            references batch_job_execution,
    create_time        timestamp    not null,
    start_time         timestamp,
    end_time           timestamp,
    status             varchar(10),
    commit_count       bigint,
    read_count         bigint,
    filter_count       bigint,
    write_count        bigint,
    read_skip_count    bigint,
    write_skip_count   bigint,
    process_skip_count bigint,
    rollback_count     bigint,
    exit_code          varchar(2500),
    exit_message       varchar(2500),
    last_updated       timestamp
);

create table if not exists batch_step_execution_context
(
    step_execution_id  bigint        not null
        primary key
        constraint step_exec_ctx_fk
            references batch_step_execution,
    short_context      varchar(2500) not null,
    serialized_context text
);

create table if not exists batch_job_execution_context
(
    job_execution_id   bigint        not null
        primary key
        constraint job_exec_ctx_fk
            references batch_job_execution,
    short_context      varchar(2500) not null,
    serialized_context text
);

create table if not exists exchange_rate
(
    base_date     date           not null,
    rate          numeric(15, 4) not null,
    currency_pair varchar(7)     not null,
    created_at    timestamp(6),
    id            bigint generated by default as identity
        primary key,
    unique (currency_pair, base_date),
    constraint uk2fqt06ll89nhej6cfi6fxnx6s
        unique (currency_pair, base_date)
);

create table if not exists index_constituent
(
    index_code     varchar(4)   not null,
    weight_percent numeric(5, 2),
    created_at     timestamp(6) not null,
    id             bigint generated by default as identity
        primary key,
    updated_at     timestamp(6),
    stock_ticker   varchar(20)  not null
);

create index if not exists idx_constituent_index
    on index_constituent (index_code);

create index if not exists idx_constituent_ticker
    on index_constituent (stock_ticker);

create table if not exists market_index
(
    created_at timestamp(6) not null,
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    index_code varchar(10)  not null
        unique,
    index_name varchar(100) not null
);

create table if not exists member
(
    created_at                timestamp(6) not null,
    id                        bigint generated by default as identity
        primary key,
    modified_at               timestamp(6),
    updated_at                timestamp(6),
    nickname                  varchar(20)  not null
        unique,
    address                   varchar(255),
    login_type                varchar(255)
        constraint member_login_type_check
            check ((login_type)::text = ANY
                   ((ARRAY ['KAKAO'::character varying, 'NAVER'::character varying, 'GOOGLE'::character varying, 'NONE'::character varying])::text[])),
    risk_level                varchar(255)
        constraint member_risk_level_check
            check ((risk_level)::text = ANY
                   ((ARRAY ['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[])),
    role                      varchar(255) not null
        constraint member_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    status                    varchar(255)
        constraint member_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'DEACTIVATED'::character varying])::text[])),
    notification_market_alert boolean      not null default false,
    notification_new_listing  boolean      not null default false,
    notification_rebalancing  boolean      not null default true
);

create table if not exists portfolio
(
    created_at  timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    member_id   bigint       not null,
    updated_at  timestamp(6),
    description varchar(255),
    name        varchar(255) not null
);

create table if not exists portfolio_item
(
    piece_count    integer        not null,
    created_at     timestamp(6)   not null,
    id             bigint generated by default as identity
        primary key,
    portfolio_id   bigint
        constraint fkdlgpfr12wdukodaavox0sq7fv
            references portfolio,
    updated_at     timestamp(6),
    asset_type     varchar(255)
        constraint portfolio_item_asset_type_check
            check ((asset_type)::text = ANY ((ARRAY ['STOCK'::character varying, 'CASH'::character varying])::text[])),
    isin_code      varchar(255)   not null,
    currency       varchar(255)   not null,
    purchase_price numeric(19, 4) not null,
    quantity       numeric(19, 4) not null,
    symbol         varchar(255)   not null,
    target_weight  numeric(7, 4)  not null
);

create table if not exists sector_insight
(
    adx                          numeric(19, 4),
    avg_fluctuation_rate         numeric(10, 2),
    base_date                    date         not null,
    bollinger_lower              numeric(19, 4),
    bollinger_mid                numeric(19, 4),
    bollinger_upper              numeric(19, 4),
    foreign_consecutive_buy_days integer,
    inst_consecutive_buy_days    integer,
    is_dead_cross                boolean,
    is_golden_cross              boolean,
    is_macd_cross                boolean,
    is_overheated                boolean      not null,
    ma120                        numeric(19, 4),
    ma20                         numeric(19, 4),
    ma5                          numeric(19, 4),
    ma60                         numeric(19, 4),
    macd                         numeric(19, 4),
    macd_signal                  numeric(19, 4),
    minus_di                     numeric(19, 4),
    plus_di                      numeric(19, 4),
    rsi14                        numeric(19, 4),
    sector_index_current_price   numeric(10, 2),
    created_at                   timestamp(6) not null,
    id                           bigint generated by default as identity
        primary key,
    net_foreign_buy_amount       bigint,
    net_inst_buy_amount          bigint,
    updated_at                   timestamp(6),
    sector_code                  varchar(10)  not null,
    alignment_status             varchar(20)
        constraint sector_insight_alignment_status_check
            check ((alignment_status)::text = ANY
                   ((ARRAY ['PERFECT'::character varying, 'REVERSE'::character varying, 'MIXED'::character varying])::text[])),
    market_type                  varchar(20)  not null
        constraint sector_insight_market_type_check
            check ((market_type)::text = ANY
                   ((ARRAY ['KOSPI'::character varying, 'KOSDAQ'::character varying, 'NASDAQ'::character varying, 'NYSE'::character varying, 'AMEX'::character varying])::text[])),
    sector_name                  varchar(50)  not null,
    leading_stocks               jsonb,
    ai_confidence_score          integer,
    ai_decision                  varchar(20)
        constraint sector_insight_ai_decision_check
            check ((ai_decision)::text = ANY
                   ((ARRAY ['BUY'::character varying, 'SELL'::character varying, 'HOLD'::character varying])::text[])),
    ai_detailed_analysis         text,
    ai_key_reasons               jsonb,
    ai_title                     varchar(500),
    constraint uk_sector_insight
        unique (sector_code, base_date)
);

create index if not exists idx_base_date
    on sector_insight (base_date);

create table if not exists stock
(
    currency                 varchar(3)            not null
        constraint stock_currency_check
            check ((currency)::text = ANY
                   ((ARRAY ['KRW'::character varying, 'USD'::character varying, 'JPY'::character varying, 'CNY'::character varying])::text[])),
    fiscal_month             varchar(2),
    is_abnormal_surge        boolean default false not null,
    is_administered          boolean default false not null,
    is_backdoor_listing      boolean default false not null,
    is_clearing_trade        boolean default false not null,
    is_invest_caution        boolean default false not null,
    is_preferred             boolean               not null,
    is_premium_tracking      boolean               not null,
    is_short_sell_overheat   boolean default false not null,
    is_short_term_overheat   boolean default false not null,
    is_trading_halt          boolean default false not null,
    is_unfaithful_disclosure boolean default false not null,
    is_warning_notice        boolean default false not null,
    listing_date             date,
    market_warning_level     varchar(2),
    group_code               varchar(5),
    market_cap_size          varchar(5),
    created_at               timestamp(6)          not null,
    id                       bigint generated by default as identity
        primary key,
    par_value                bigint,
    updated_at               timestamp(6),
    sector_large_code        varchar(10),
    sector_medium_code       varchar(10),
    sector_small_code        varchar(10),
    market_type              varchar(20)           not null
        constraint stock_market_type_check
            check ((market_type)::text = ANY
                   ((ARRAY ['KOSPI'::character varying, 'KOSDAQ'::character varying, 'NASDAQ'::character varying, 'NYSE'::character varying, 'AMEX'::character varying])::text[])),
    standard_code            varchar(20),
    status                   varchar(20)           not null
        constraint stock_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'HALTED'::character varying, 'ADMINISTRATIVE'::character varying, 'DELISTED'::character varying])::text[])),
    ticker                   varchar(20)           not null
        unique
        constraint idx_stock_ticker
            unique,
    name                     varchar(100)          not null,
    sector_name              varchar(100)
);

create table if not exists dividend_history
(
    amount       numeric(19, 4),
    currency     varchar(3) not null
        constraint dividend_history_currency_check
            check ((currency)::text = ANY
                   ((ARRAY ['KRW'::character varying, 'USD'::character varying, 'JPY'::character varying, 'CNY'::character varying])::text[])),
    ex_date      date       not null,
    payment_date date,
    created_at   timestamp(6),
    id           bigint generated by default as identity
        primary key,
    stock_id     bigint     not null
        constraint fkjyhajsttktety73p35v4nnpgf
            references stock,
    constraint uq_dividend_stock_date
        unique (stock_id, ex_date)
);

create table if not exists market_signal
(
    base_date   date         not null,
    intensity   numeric(10, 2),
    is_analyzed boolean      not null,
    analyzed_at timestamp(6),
    created_at  timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    stock_id    bigint       not null
        constraint fkjqgsccm9vwqw9q1d1derw8jxn
            references stock,
    updated_at  timestamp(6),
    signal_type varchar(30)  not null
        constraint market_signal_signal_type_check
            check ((signal_type)::text = ANY
                   ((ARRAY ['VOLUME_SPIKE'::character varying, 'LIQUIDITY_SURGE'::character varying, 'GOLDEN_CROSS'::character varying, 'RSI_OVERSOLD'::character varying])::text[])),
    ai_summary  text
);

create index if not exists idx_stock_name
    on stock (name);

create index if not exists idx_stock_status
    on stock (status);

create index if not exists idx_stock_ticker_name
    on stock (ticker, name);

create table if not exists stock_price
(
    adj_close_price  numeric(19, 4),
    adx              numeric(19, 4),
    base_date        date         not null,
    bollinger_lower  numeric(19, 4),
    bollinger_mid    numeric(19, 4),
    bollinger_upper  numeric(19, 4),
    close_price      numeric(19, 4),
    high_price       numeric(19, 4),
    is_dead_cross    boolean,
    is_golden_cross  boolean,
    is_macd_cross    boolean,
    low_price        numeric(19, 4),
    ma120            numeric(19, 4),
    ma20             numeric(19, 4),
    ma5              numeric(19, 4),
    ma60             numeric(19, 4),
    macd             numeric(19, 4),
    macd_signal      numeric(19, 4),
    minus_di         numeric(19, 4),
    open_price       numeric(19, 4),
    plus_di          numeric(19, 4),
    prev_close_price numeric(19, 4),
    rsi14            numeric(19, 4),
    transaction_amt  numeric(25, 2),
    created_at       timestamp(6) not null,
    stock_id         bigint       not null
        constraint fk81fdh1tk8jopdbf39rrvlmwpq
            references stock,
    volume           bigint,
    alignment_status varchar(20)
        constraint stock_price_alignment_status_check
            check ((alignment_status)::text = ANY
                   ((ARRAY ['PERFECT'::character varying, 'REVERSE'::character varying, 'MIXED'::character varying])::text[])),
    primary key (base_date, stock_id)
);

create index if not exists idx_stock_price_lookup
    on stock_price (stock_id asc, base_date desc);

create index if not exists idx_stock_price_indicators
    on stock_price (base_date, alignment_status, rsi14);

create table if not exists watchlist_group
(
    created_at timestamp(6) not null,
    deleted_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    member_id  bigint       not null
        constraint fkmxw0diga6q0cy587tkvjxka1p
            references member,
    updated_at timestamp(6),
    name       varchar(50)  not null
);

create table if not exists watchlist_item
(
    created_at         timestamp(6) not null,
    deleted_at         timestamp(6),
    id                 bigint generated by default as identity
        primary key,
    stock_id           bigint       not null
        constraint fkl1x0ohifuprs98khdpwag6xvk
            references stock,
    updated_at         timestamp(6),
    watchlist_group_id bigint       not null
        constraint fkgeb957x7qvorlpa6tlbf6vm6k
            references watchlist_group,
    market_type        varchar(20)  not null
        constraint watchlist_item_market_type_check
            check ((market_type)::text = ANY
                   ((ARRAY ['KOSPI'::character varying, 'KOSDAQ'::character varying, 'NASDAQ'::character varying, 'NYSE'::character varying, 'AMEX'::character varying])::text[])),
    note               varchar(200),
    ticker             varchar(20)  not null
);

create table if not exists advisor_reports
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6),
    action       varchar(255) not null
        constraint advisor_reports_action_check
            check ((action)::text = ANY
                   ((ARRAY ['REBALANCE'::character varying, 'RISK_MANAGEMENT'::character varying, 'TECHNICAL_OPTIMIZATION'::character varying, 'DIVERSIFICATION'::character varying])::text[])),
    content      text         not null,
    portfolio_id bigint       not null
        constraint fkhltcep7vfwks8pev46380oknf
            references portfolio
);

create table if not exists portfolio_stats
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6),
    base_date    date         not null,
    beta         numeric(7, 4),
    mdd          numeric(7, 4),
    sharpe_ratio numeric(7, 4),
    portfolio_id bigint       not null
        constraint ukjbidncxtypj4i3tbjhbemnxa
            unique
        constraint fkchd5wi50w1dl7dt4a4bfl1kgx
            references portfolio
);
