-- Additive staging schema for source-verified EOD data.
-- Legacy stock_price / stock_investor_trade remain untouched until a verified key/scope cutover.
CREATE TABLE stock_price_eod (
    stock_id bigint NOT NULL REFERENCES stock(id),
    trade_date date NOT NULL,
    quote_scope varchar(10) NOT NULL CHECK (quote_scope IN ('KRX','NXT','UNIFIED','LOCAL')),
    open_price numeric(19,4) CHECK (open_price >= 0),
    high_price numeric(19,4) CHECK (high_price >= 0),
    low_price numeric(19,4) CHECK (low_price >= 0),
    close_price numeric(19,4) CHECK (close_price >= 0),
    previous_close_price numeric(19,4) CHECK (previous_close_price >= 0),
    volume bigint CHECK (volume >= 0),
    trading_amount numeric(25,2) CHECK (trading_amount >= 0),
    no_trade boolean,
    source_api varchar(50) NOT NULL,
    data_status varchar(20) NOT NULL CHECK (data_status IN ('PROVISIONAL','FINAL','INCOMPLETE')),
    collected_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    corrected_at timestamptz,
    data_revision integer NOT NULL DEFAULT 1 CHECK (data_revision > 0),
    PRIMARY KEY (stock_id, trade_date, quote_scope),
    CHECK (data_status <> 'FINAL' OR close_price IS NOT NULL),
    CHECK (high_price IS NULL OR low_price IS NULL OR high_price >= low_price)
);
CREATE INDEX idx_stock_price_eod_date ON stock_price_eod(trade_date, quote_scope, stock_id);
COMMENT ON TABLE stock_price_eod IS 'Source-verified scoped EOD quotes; legacy stock_price remains active until cutover.';
COMMENT ON COLUMN stock_price_eod.previous_close_price IS 'Provider prior close; may differ from LAG(close) around corporate actions.';

CREATE TABLE stock_price_adjustment_eod (
    stock_id bigint NOT NULL,
    trade_date date NOT NULL,
    quote_scope varchar(10) NOT NULL,
    adjusted_close_price numeric(19,4) CHECK (adjusted_close_price >= 0),
    adjustment_basis varchar(30) NOT NULL DEFAULT 'UNKNOWN'
        CHECK (adjustment_basis IN ('NONE','SPLIT','PROVIDER_ADJUSTED','TOTAL_RETURN','UNKNOWN')),
    adjustment_as_of date,
    source_api varchar(50) NOT NULL,
    data_status varchar(20) NOT NULL CHECK (data_status IN ('PROVISIONAL','FINAL','INCOMPLETE')),
    collected_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    corrected_at timestamptz,
    data_revision integer NOT NULL DEFAULT 1 CHECK (data_revision > 0),
    PRIMARY KEY (stock_id, trade_date, quote_scope),
    FOREIGN KEY (stock_id, trade_date, quote_scope)
        REFERENCES stock_price_eod(stock_id, trade_date, quote_scope),
    CHECK (adjusted_close_price IS NULL OR adjustment_as_of IS NOT NULL),
    CHECK (data_status <> 'FINAL' OR adjusted_close_price IS NOT NULL)
);
COMMENT ON TABLE stock_price_adjustment_eod IS 'Independent adjustment observation; collection date is not an adjustment as-of date.';
COMMENT ON COLUMN stock_price_adjustment_eod.adjustment_basis IS 'PROVIDER_ADJUSTED does not guarantee total return and must not imply dividend reinvestment.';

CREATE TABLE stock_technical_indicator_eod (
    stock_id bigint NOT NULL,
    trade_date date NOT NULL,
    quote_scope varchar(10) NOT NULL,
    ma5 numeric(19,4), ma20 numeric(19,4), ma60 numeric(19,4), ma120 numeric(19,4),
    rsi14 numeric(10,4) CHECK (rsi14 BETWEEN 0 AND 100),
    macd numeric(19,4), macd_signal numeric(19,4),
    bollinger_upper numeric(19,4), bollinger_mid numeric(19,4), bollinger_lower numeric(19,4),
    adx numeric(10,4), plus_di numeric(10,4), minus_di numeric(10,4),
    alignment_status varchar(20) CHECK (alignment_status IN ('PERFECT','REVERSE','MIXED')),
    is_golden_cross boolean, is_dead_cross boolean, is_macd_cross boolean,
    calculation_version varchar(40) NOT NULL,
    input_data_version varchar(100) NOT NULL,
    calculated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (stock_id, trade_date, quote_scope),
    FOREIGN KEY (stock_id, trade_date, quote_scope)
        REFERENCES stock_price_eod(stock_id, trade_date, quote_scope)
);
CREATE INDEX idx_stock_technical_indicator_eod_filter
    ON stock_technical_indicator_eod(trade_date, quote_scope, alignment_status, rsi14);

CREATE TABLE stock_ai_analysis_eod (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id bigint NOT NULL,
    trade_date date NOT NULL,
    quote_scope varchar(10) NOT NULL,
    content text NOT NULL,
    model_version varchar(100) NOT NULL,
    prompt_version varchar(100) NOT NULL,
    input_data_version varchar(100) NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stock_id, trade_date, quote_scope)
        REFERENCES stock_price_eod(stock_id, trade_date, quote_scope)
);
CREATE INDEX idx_stock_ai_analysis_eod_latest
    ON stock_ai_analysis_eod(stock_id, trade_date DESC, generated_at DESC);

CREATE TABLE stock_investor_trade_eod (
    stock_id bigint NOT NULL REFERENCES stock(id),
    trade_date date NOT NULL,
    quote_scope varchar(10) NOT NULL CHECK (quote_scope IN ('KRX','NXT','UNIFIED','LOCAL')),
    foreign_net_quantity bigint,
    institution_net_quantity bigint,
    foreign_net_amount numeric(25,2),
    institution_net_amount numeric(25,2),
    data_status varchar(20) NOT NULL CHECK (data_status IN ('PROVISIONAL','FINAL','INCOMPLETE')),
    source_api varchar(50) NOT NULL,
    collected_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    corrected_at timestamptz,
    data_revision integer NOT NULL DEFAULT 1 CHECK (data_revision > 0),
    PRIMARY KEY (stock_id, trade_date, quote_scope),
    CHECK (data_status <> 'FINAL' OR (
        foreign_net_quantity IS NOT NULL AND institution_net_quantity IS NOT NULL
        AND foreign_net_amount IS NOT NULL AND institution_net_amount IS NOT NULL))
);
CREATE INDEX idx_foreign_net_amount_eod
    ON stock_investor_trade_eod(trade_date, quote_scope, foreign_net_amount DESC, stock_id);
CREATE INDEX idx_institution_net_amount_eod
    ON stock_investor_trade_eod(trade_date, quote_scope, institution_net_amount DESC, stock_id);
COMMENT ON TABLE stock_investor_trade_eod IS 'Four independently sourced foreign/institution net-flow values; negative values are valid.';
COMMENT ON COLUMN stock_investor_trade_eod.foreign_net_amount IS 'KRW won; normalize provider units once before persistence.';
