create table outbox_event
(
    id           bigint generated by default as identity primary key,
    topic        varchar(255) not null,
    payload      text         not null,
    status       varchar(20)  not null,
    processed_at timestamp,
    error_message text,
    created_at   timestamp    not null,
    updated_at   timestamp
);

create index idx_outbox_event_status on outbox_event (status);
